// Kaynak: resources/templates/4-kabul-ve-odeme-islemleri\hakedis-raporu\index.html.json
export interface IHakedisRaporu {
  solLogo?: string
  sagLogo?: string
  antetSatir1?: string
  kurumAdi?: string
  isinAdi?: string
  hakedisNo?: string
  hakedisTarihi?: string
  hizmetTutari?: string
  fiyatFarkTutari?: string
  toplamTutar?: string
  iskontoTutari?: string
  oncekiHakedisTutari?: string
  buHakedisTutari?: string
  kdvOrani?: string
  kdvTutari?: string
  tahakkukTutari?: string
  gelirVergisiOrani?: string
  gelirVergisiTutari?: string
  damgaVergisiOrani?: string
  damgaVergisiTutari?: string
  kdvTevkifatiOrani?: string
  kdvTevkifatTutari?: string
  sskKesintisi?: string
  idareMakineKiralari?: string
  gecikmeCezasi?: string
  avansMahsubu?: string
  fiyatFarkTeminatKesintisi?: string
  stopajTutari?: string
  digerKesinti1Adi?: string
  digerKesinti1Tutari?: string
  digerKesinti2Adi?: string
  digerKesinti2Tutari?: string
  kesintilerToplamTutari?: string
  odenecekTutar?: string
  notlar?: string
  yukleniciGoster?: boolean
  yukleniciFirma?: string
  duzenleyen1Adi?: string
  duzenleyen1Unvan?: string
  duzenleyen2Adi?: string
  duzenleyen2Unvan?: string
  duzenleyen3Adi?: string
  duzenleyen3Unvan?: string
  onayTarihi?: string
  onaylayanPersonelAdi?: string
  onaylayanPersonelUnvan?: string
}
